version: '3.1'

services:
  # SERVICES
  registry-service:
    build:
      context: ./registry-service
    volumes: 
      - ./registry-service/services.json:/usr/app/services.json
    ports:
      - "3000:3000"
    networks:
      - microservice
  storage-service:
    build:
      context: ./storage-service
    environment: 
      DB_HOST: database
      DB_PORT: 27017
      DB_NAME: $DB_NAME
      DB_MAIN_TABLE: $DB_MAIN_TABLE
      WAIT_HOSTS: database:27017
      # DB_ROOT_USERNAME: admin
      # DB_ROOT_PASSWORD: admin
    ports:
      - "3001:3001"
    depends_on:
      - database
    restart: always
    networks:
      - microservice
  
    # DEPENDENCIES
  database:
    image: mongo:latest
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - microservice

networks:
  microservice:
    driver: bridge