version: '3.1'

services:
  # SERVICES
  registry-service:
    build:
      context: ./registry-service
    ports:
      - "3000:3000"
    networks:
      - microservice
  storage-service:
    build:
      context: ./storage-service
    env_file:
      - .env
    environment: 
      DB_HOST: database
      DB_PORT: 27017
      DB_NAME: m_db
      # DB_ROOT_USERNAME: admin
      # DB_ROOT_PASSWORD: admin
    ports:
      - "3001:3001"
    # volumes:
    #   - ./wait-for-it.sh:/usr/wait-for-it.sh
    # command: sh -c '/usr/wait-for-it.sh database:27017 -- yarn start:prod'
    depends_on:
      - database
    restart: always
    networks:
      - microservice
  
    # DEPENDENCIES
  database:
    image: mongo:latest
    env_file:
      - .env
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - microservice



networks:
  microservice:
    driver: bridge