{
 "title": "Service Monitoring",
 "tags": [ "microservice" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Service", "query": "label_values(up, instance)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Proccess CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "CPU  System"
    },
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "CPU User"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "Event Loop Lag"
    }
   ]
  },
  {
   "title": "NodeJS version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "nodejs_version_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{instance=~\"$instance\"}) / sum(http_request_duration_seconds_count{instance=~\"$instance\"})",
     "legendFormat": "Average Response Time"
    }
   ]
  },
  {
   "title": "System Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=\"5XX\", instance=~\"$instance\"}[1m])) /  sum(increase(http_request_duration_seconds_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "System Error Rate"
    }
   ]
  },
  {
   "title": "Thorughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[1m])) by (route, method, code) * 60",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  }
 ]
}