apps:
  - script   : './build/index.js'
    name     : 'auth-service'
    instances: 2
    exec_mode: cluster
    env    :
      NODE_ENV: development
    env_production:
      NODE_ENV: production
   