http.host: 0.0.0.0
path.config: /usr/share/logstash/pipeline/*.conf
xpack.monitoring.elasticsearch.hosts:
- http://elasticsearch:9200
xpack.monitoring.elasticsearch.password: admin
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
